// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhm13eWMTIDo0ZcRjoVROddh9I7d05vbA',
    appId: '1:87606701964:web:4115e33ba541f9eb28b0a9',
    messagingSenderId: '87606701964',
    projectId: 'doc555-1d2c9',
    authDomain: 'doc555-1d2c9.firebaseapp.com',
    storageBucket: 'doc555-1d2c9.appspot.com',
    measurementId: 'G-9VW1KGJ33D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6CowHwJ7rwhgmJHW2XmXc1d05t8CAQ-Q',
    appId: '1:87606701964:android:9a7b2037f386454428b0a9',
    messagingSenderId: '87606701964',
    projectId: 'doc555-1d2c9',
    storageBucket: 'doc555-1d2c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD92PdyYvlIzxuRVvx7A1W1GYwj0olItuk',
    appId: '1:87606701964:ios:ec552c4c58d8ba7428b0a9',
    messagingSenderId: '87606701964',
    projectId: 'doc555-1d2c9',
    storageBucket: 'doc555-1d2c9.appspot.com',
    iosClientId: '87606701964-cd91er1epje5qrqfj5d7vold28hngn70.apps.googleusercontent.com',
    iosBundleId: 'com.example.doc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD92PdyYvlIzxuRVvx7A1W1GYwj0olItuk',
    appId: '1:87606701964:ios:ec552c4c58d8ba7428b0a9',
    messagingSenderId: '87606701964',
    projectId: 'doc555-1d2c9',
    storageBucket: 'doc555-1d2c9.appspot.com',
    iosClientId: '87606701964-cd91er1epje5qrqfj5d7vold28hngn70.apps.googleusercontent.com',
    iosBundleId: 'com.example.doc',
  );
}
